### 리스트 생성 방법 ###

### 리스트 컴프리헨션 ###  
  
  
##### 리스트 컴프리헨션 동작순서 #####  


1. 반복가능한 객체로부터 값을 하나 꺼내와서 변수에 담음  

2. 요소를 담은 변수를 활용해서 표현식을 실행  
    (이때 변수는 활용할수도, 활용하지 않을수도)  
    
3. 표현식 결과 값을 리스트 요소에 넣기  

4. 반복가능한 객체로부터 값이 없을 때까지 1~3 과정을 반복

list_variable = [expression for 변수 in iterrable]

In [3]:
#range --> 1, 2, ... , 9
#_ --> _ = 1, ... _=9
list_a = [_**2 for _ in range(1, 10)]
print(list_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [5]:
list_b = [print("Hello world") for _ in range(10)]

Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world
Hello world


In [7]:
list_c = []
for _ in range(1, 10):
    list_c.append(_**2)
print(list_c)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
list_d = [_**2 for _ in range(1,10)] #range : 값을 하나씩 줌 (이상, 미만)
print(list_d)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [11]:
prac_result = [_**2 for _ in range(1,10)]
print(type(prac_result))
print(prac_result)

<class 'list'>
[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [77]:
prac_result2 = [_ for _ in range(1, 10, 2)]
print(prac_result2)

[1, 3, 5, 7, 9]


In [96]:
prac_result3 = [i for i in 'a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s, t, u, v , w, x, y, z ']
print(prac_result3)

['a', ',', ' ', 'b', ',', ' ', 'c', ',', ' ', 'd', ',', ' ', 'e', ',', ' ', 'f', ',', ' ', 'g', ',', ' ', 'h', ',', ' ', 'i', ',', ' ', 'j', ',', ' ', 'k', ',', ' ', 'l', ',', ' ', 'm', ',', ' ', 'n', ',', ' ', 'o', ',', ' ', 'p', ',', ' ', 'q', ',', ' ', 'r', ',', ' ', 's', ',', ' ', 't', ',', ' ', 'u', ',', ' ', 'v', ' ', ',', ' ', 'w', ',', ' ', 'x', ',', ' ', 'y', ',', ' ', 'z', ' ']


In [110]:
prac_result4 = [str(_) for _ in range (2,11)] + [i for i in 'JQKA']
print(prac_result4)

['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']


In [122]:
prac_result4 = [str(_) for _ in range (2,11)]
prac_result4.extend([i for i in 'JQKA'])
print(prac_result4)

['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']


In [132]:
prac_result5 = [prac_result4 for _ in range (4)]
print(prac_result5)

[['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'], ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'], ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'], ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']]


In [133]:
prac_result4[0] = 'two' # 0번째 요소인 '2'의 값 'two'로 변경
print(prac_result4)

['two', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']


In [134]:
print(prac_result5) # 각각 다른 객체를 바라보기엔 필요한 메모리가 너무 커져 보다 효율적이기 위해 
                    # 모두 동일한 객체를 바라보고 있기 떄문에 변수 하나만 변경해도 모두 변경

[['two', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'], ['two', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'], ['two', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'], ['two', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']]


In [135]:
                  prac_result5[0]
prac_result4      prac_result5[1]
                  prac_result5[2]
                  prac_result5[3]

SyntaxError: invalid syntax (3108794452.py, line 2)

### id 내장함수 ###
  
      
##### 객체마다 구분할 수 있는 고유한 정수 값(메모리 주소)을 갖습니다.  그걸 조회하는 게 id() 내장 함수 #####
##### 즉 id()로 가져온 정수 값이 같다면 같은 객체 #####
즉 변수와 모든 요쇼들이 같은 메모리상의 객체를 바라봄


In [140]:
print("prac_result4의 id", id(prac_result4))

for i, v in enumerate(prac_result5):
    print("prac_result5[",i,"]: ", id(v), sep="")

prac_result4의 id 2232063335040
prac_result5[0]: 2232063335040
prac_result5[1]: 2232063335040
prac_result5[2]: 2232063335040
prac_result5[3]: 2232063335040


In [139]:
prac_result6 = [prac_result4[:] for _ in range(4)]

print("prac_result4의 id", id(prac_result4))
for i, v in enumerate(prac_result6):
    print("prac_result6[",i,"]: ", id(v), sep="")

prac_result4의 id 2232063335040
prac_result6[0]: 2232096271424
prac_result6[1]: 2232064360320
prac_result6[2]: 2232063346368
prac_result6[3]: 2232096271616


#### 리스트변수[:] → 새로운 객체를 만들어 반환한다. ####

### id내장함수 연습문제 ###

In [158]:
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
old_list = list(range(10))
new_list = old_list[:]

print(id(old_list))
print(id(new_list))
print(old_list is new_list) # is -> false 아이디와 아이디 비교 / 각각 바라보는 객체가 다르다.
print(old_list == new_list) # == -> true 값과 값 비교 / 객체 상관없이 단순하게 값이 같다.

2232096984064
2232063420096
False
True


In [152]:
list_sample = [_ for _ in range(0,30)]
# range (시작, 끝, 증감)
# 시퀸스자료형변수 [시작:끝:증감]
# 시작 생략 - 시작부터 끝 생략 = 마지막까지 증감 + = 1
print(list_sample[:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [154]:
#문자열이나 튜플은 복사해도 주소가 변경이 안된다. 리스트만 가능 

str_sample = "This is str"
str2 = str_sample[:]

print(id(str_sample))
print(id(str2))

2232108241072
2232108241072


In [159]:
str_a = "hello"
str_b = "hello"
print(id(str_a))
print(id(str_b))

2232059555120
2232059555120


#### java에서는 반대 ####  
  
java에서의 == 연산자 -> 값을 비교
python에서의 == 연산 -> 비교 연산자가 맞지만 메모리주소 비교

In [165]:
import time
curr = time.time()

for _ in range(100000):
    [i for i in range(1000)]

last = time.time()
print(last - curr)    

2.222635507583618


In [164]:
import time
curr = time.time()

for _ in range(100000):
    list(i for i in range(1000))

last = time.time()
print(last - curr)    

3.5149691104888916


#### 연습문제 ####

In [264]:
print("실행 결과:")
n = int(input("순환할 숫자를 입력하세요:"))
num = [i for i in range(1, n+1)]
    
for j in range(len(num)):
    j = 0
    for i in num:
        print(i, end=" ")
    print()
    num.append(num[j])
    num.remove(num[j])

실행 결과:


순환할 숫자를 입력하세요: 10


1 2 3 4 5 6 7 8 9 10 
2 3 4 5 6 7 8 9 10 1 
3 4 5 6 7 8 9 10 1 2 
4 5 6 7 8 9 10 1 2 3 
5 6 7 8 9 10 1 2 3 4 
6 7 8 9 10 1 2 3 4 5 
7 8 9 10 1 2 3 4 5 6 
8 9 10 1 2 3 4 5 6 7 
9 10 1 2 3 4 5 6 7 8 
10 1 2 3 4 5 6 7 8 9 


In [265]:
num = int(input("순환할 숫자를 입력하세요:"))
for i in range(1, num + 1):
    for j in range(i, num + i):
        if j % num == 0:
            print(num, end=" ")
        else:
            print(j % num, end=" ")
    print()

순환할 숫자를 입력하세요: 10


1 2 3 4 5 6 7 8 9 10 
2 3 4 5 6 7 8 9 10 1 
3 4 5 6 7 8 9 10 1 2 
4 5 6 7 8 9 10 1 2 3 
5 6 7 8 9 10 1 2 3 4 
6 7 8 9 10 1 2 3 4 5 
7 8 9 10 1 2 3 4 5 6 
8 9 10 1 2 3 4 5 6 7 
9 10 1 2 3 4 5 6 7 8 
10 1 2 3 4 5 6 7 8 9 


In [166]:
list_g = list(range(100))
list_f = list_g.copy()

# 리스트 복사(copy()) 메서드) #

In [266]:
list_g = list(range(10))
list_h = list_g.copy()
print(id(list_g))
print(id(list_h))
print(list_g is list_h)

2232097087552
2232097065152
False


### 얕은복사 ###  
  
  >변수처럼 주소를 복사

> 얕은 복사 : 값만 복사  
> 깊은 복사 : 안에 있는 주소까지 같이 복사

In [271]:
list_i =[[0]]*3
print(list_i)

[[0], [0], [0]]


In [272]:
list_i[0][0]  = 999 #[0][0] =>리스트 안에 리스트가 있음

In [274]:
list_i[0][0]  = 999
print(list_i)

[[999], [999], [999]]


In [286]:
list_i[0][0] is list_i[1][0]        #list_i[0][0] list 0번자리 속 list의 0번자리 수
list_i[0][0] is list_i[2][0]        #list_i[1][0] list 1번자리 속 list의 0번자리 수
                                    #list_i[2][0] list 2번자리 속 list의 0번자리 수

True

In [283]:
list_j = [[1,2], [3,4]]
list_k = list_j[:] #[:] --> 리스트 복사
print(list_k[0] is  list_j[0])

True


In [284]:
list_j[0][1] = 2**2 # list_j[0][1] ---> list 0번 자리 list 속의 1번 자리 수
print(list_j)
print(list_k)

[[1, 4], [3, 4]]
[[1, 4], [3, 4]]


In [287]:
list_l = [[5,6], [7,8]]
list_m = list_l.copy() #[:] --> 리스트 복사 #얕은 복사
print(list_l[0] is  list_m[0]) # 두칸 밑 식이랑 비교

True


In [288]:
list_l[0][1] = 999
print(list_l)
print(list_m)

[[5, 999], [7, 8]]
[[5, 999], [7, 8]]


### 깊은 복사 ###  
  
    
>전혀 다른 메모리 공간을 차지하는 완전한 리스트   
>두 리스트 간의 값은 같으나 객체는 완전히 다름

> 얕은 복사 : 값만 복사  
> 깊은 복사 : 안에 있는 주소까지 같이 복사

In [292]:
import copy
list_n = [[9, 10], [11, 12]] # 두칸 위 식이랑 비교 
list_o = copy.deepcopy(list_n) #깊은 복사
print(list_n[0] is list_o[0]) 

False


In [293]:
print(list_n[1][0])
print([11, 12][0])

11
11


In [294]:
list_n[1][0] = 999
print(list_n)   #얕은 복사는 list_o도 함께 변하지만 
print(list_o)   #깊은 복사는 새로운 객체를 만들어 주기때문에 list_o은 변하지 않음

[[9, 10], [999, 12]]
[[9, 10], [11, 12]]


#### [얕은 복사일때] #### 

list_n[1][0] = 999  
print(list_n)    
print(list_o)  

--------
결과값  

[[9, 10], [11, 12]]  
[[9, 10], [11, 12]]  
  
  
#### [깊은 복사일때] ####   
  
list_n[1][0] = 999  
print(list_n)    
print(list_o)    

--------
결과값  

[[9, 10], [999, 12]]  
[[9, 10], [11, 12]] 


### for문과 if문이 동시에 있는 리스트 컴프리헨션 동작 순서###   
    
    
> 1. 반복가능한 객체로 부터 값을 하나 꺼내와서 조건식에 넣기  
> 2. 조건식이 true이면 변수를 활용해서 표현식을 실행      
   (변수 활용 해도되고 안해도됨)  
> 3. 조건식이 false면 1번부터 다시 시작  
> 4. 표현식 결과 값을 리스트 요소애 넣기  
> 5. 반복가능한 객체로부터 값이 없을때까지 1-3 반복   
  
    
lkist_variable = [expressio for 변수 interable if 조건식]      ///#true 일때만

In [309]:
list_p = [i for i in range(10) if i % 3 == 0]
print(list_p)

[0, 3, 6, 9]


#####중첩 리스트 사용하기####  
  
  
[expressio for 변수 in interable  

         for 변수 in interable  
         for 변수 in interable  
         for 변수 in interable]   
  
    
<가독성을 위해 줄바꿈>

In [311]:
easy_list = [[1, 2, 3, 4, 5],[3, 4]]
for item in easy_list:
    for i in item:
        print(i)

1
2
3
4
5
3
4


In [312]:
easy_list = [[1, 2, 3, 4, 5], [3, 4]]
i = 0 # easy_list 인덱스용

while i < len(easy_list):
    j = 0 #easy_list[0], easy list[1] 인덱스용
    while j <len(easy_list[i]):
        print(easy_list[i][j])
        j+=1
    i+=1

1
2
3
4
5
3
4


In [313]:
generator_variable = (_ for _ in range(10))
print(generator_variable)
print(type(generator_variable))
#iterable
#tuple(인수), list(인수)
hesattr(generator_variable, "_iter_")

<generator object <genexpr> at 0x00000207B3AC9C10>
<class 'generator'>


In [325]:
a = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']
b = [i for i in a if len(i) == 5]
print(b)

['alpha', 'bravo', 'delta', 'hotel', 'india']


In [374]:
print("실행 결과:")
a, b = map(int,input("정수 두 개 입력하세요.:").split())   

if 1 <= a <= 20 :
    if 10 <= b <= 30 :
        if a < b:
            list_nu = [2**i for i in range(a,b+1)]
            print(list_nu)
            list_nu.remove(list_nu[1])
            list_nu.remove(list_nu[-2])
            print(list_nu)
        else:
            print("첫 번째 입력 값은 두 번째 입력값보다 작게 입력하세요")
    else : 
        print("두 번째 값의 범위는 10 ~ 30입니다.")
else :
    print("첫 번째 값의 범위는 1 ~ 20입니다.")    
    

실행 결과:


정수 두 개 입력하세요.: 10 20


[1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576]
[1024, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 1048576]


In [12]:
print("실행 결과:")
num = 1
line = 0
total = 0
while num <= 100 :
    if num % 2 == 0 :
        total += num * num
        print("+", num * num, end=" ")
    else:
        total -= num * num
        print("-", num * num, end=" ")
    num += 1
    line += 1
    if line == 10 :
        line = 0
        print()
    
print("=", total, "입니다")

실행 결과:
- 1 + 4 - 9 + 16 - 25 + 36 - 49 + 64 - 81 + 100 
- 121 + 144 - 169 + 196 - 225 + 256 - 289 + 324 - 361 + 400 
- 441 + 484 - 529 + 576 - 625 + 676 - 729 + 784 - 841 + 900 
- 961 + 1024 - 1089 + 1156 - 1225 + 1296 - 1369 + 1444 - 1521 + 1600 
- 1681 + 1764 - 1849 + 1936 - 2025 + 2116 - 2209 + 2304 - 2401 + 2500 
- 2601 + 2704 - 2809 + 2916 - 3025 + 3136 - 3249 + 3364 - 3481 + 3600 
- 3721 + 3844 - 3969 + 4096 - 4225 + 4356 - 4489 + 4624 - 4761 + 4900 
- 5041 + 5184 - 5329 + 5476 - 5625 + 5776 - 5929 + 6084 - 6241 + 6400 
- 6561 + 6724 - 6889 + 7056 - 7225 + 7396 - 7569 + 7744 - 7921 + 8100 
- 8281 + 8464 - 8649 + 8836 - 9025 + 9216 - 9409 + 9604 - 9801 + 10000 
= 5050 입니다


### random 라이브러리 ###  
  
    
random randint(시작정수, 끝정수)함수를 활용하면 시작 정수(포함)부터 끝정수(포함)까지의 범위의 난수(랜덤한 수)를 생성


In [3]:
import random 
random_list = [random.randint(1, 2) for _ in range(10)]
print(random_list)

[2, 1, 1, 2, 2, 1, 2, 2, 1, 2]


In [43]:
print("실행 결과:")
num = int(input("로또 번호 몇개 드릴까요?"))
for i in range(0, num) :
    ran_list = [random.randint(1, 45) for _ in range(6)]
    ran_list.sort()
    for j in range(0, 5) :
        if ran_list[j] == ran_list[j+1] :
            ran_list.clear()
            for k in range(1, 2) :
                ran_list = [random.randint(1, 45) for _ in range(6)]
                ran_list.sort()
            print(ran_list)
                

실행 결과:


로또 번호 몇개 드릴까요? 5


[4, 11, 24, 33, 39, 42]


In [10]:
ran_list = [random.randint(1, 45) for _ in range(6)]

In [39]:
for j in range (0, num-1)
            if ran_list[j] ==

SyntaxError: invalid syntax (1584206570.py, line 1)

In [79]:
print("실행 결과:")
num = int(input("로또 번호 몇개 드릴까요?"))
for i in range(0, num) :
    ran_list = [random.randint(1, 45) for _ in range(6)]
    ran_list.sort()
    for j in range(0, 5) :
        if ran_list[j] == ran_list[j+1] :
            del ran_list
            ran_list = [random.randint(1, 45) for _ in range(6)]
            ran_list.sort()
        
    print(ran_list)

실행 결과:


로또 번호 몇개 드릴까요? 6


[7, 8, 10, 16, 33, 41]
[1, 10, 29, 39, 41, 44]
[1, 8, 25, 31, 35, 36]
[1, 9, 22, 22, 29, 41]
[16, 18, 25, 28, 33, 45]
[3, 5, 6, 19, 22, 25]


### [ 다른 사람 풀이 ] ### 

In [85]:
print("실행 결과:")
import numpy as np
num = int(input("로또 번호 몇개 드릴까요?"))
for i in range(0, num) :
    random_li = np.random.choice(range(1, 46), 6, replace = False, p = [1/45] * 45)
    print(random_li)


실행 결과:


로또 번호 몇개 드릴까요? 5


[33  5 17 10 18 35]
[11 26  4 34 10 39]
[ 3 23  8 15 12 36]
[28 19 38 41 23 29]
[36  4 12 33 43  7]


In [93]:
print("실행 결과:")
num = int(input("로또 번호 몇개 드릴까요?"))
for i in range(0, num) :
    ran_list = random.sample(range(1,46),6)
    ran_list.sort()
    print(ran_list)

실행 결과:


로또 번호 몇개 드릴까요? 2


[5, 20, 26, 30, 33, 34]
[5, 18, 20, 29, 39, 43]


In [98]:
import random

count = int(input("로또 번호 몇 개 드릴까요?"))

for i in range(count):
    lotto_numbers = []
    while len(lotto_numbers) < 6:
        lotto_number = random.randint(1, 45)
        if lotto_number not in lotto_numbers:
            lotto_numbers.append(lotto_number)
    lotto_numbers.sort()
    print(lotto_numbers)

로또 번호 몇 개 드릴까요? 5


[15, 19, 24, 25, 35, 38]
[11, 19, 26, 27, 32, 37]
[11, 26, 33, 37, 38, 40]
[3, 12, 17, 40, 44, 45]
[1, 6, 9, 24, 29, 37]


In [101]:
import random

count = int(input("로또 번호 몇 개 드릴까요?"))

for i in range(count):
    lotto = [j for j in range(1, 46)]
    lotto_numbers = []
    for _ in range(6):
        lotto_number = lotto[random.randint(1, len(lotto)-1 )]
        lotto_numbers.append(lotto_number)
        lotto.remove(lotto_number)
        lotto_numbers.sort()
        
    print(lotto_numbers)

로또 번호 몇 개 드릴까요? 5


[3, 10, 12, 33, 37, 42]
[8, 13, 22, 33, 36, 38]
[7, 11, 13, 24, 33, 44]
[17, 18, 27, 31, 37, 39]
[8, 10, 19, 20, 25, 29]
