<h1> 2023 - 01 -16 </h1>

<h1> <mark>[ 넘파이 배열 ]</mark> </h1>

Numpy는 파이썬 내장 모듈이 아님 따라서 별도 설치 요구   
아나콘다를 환경으로 꾸리면 기본적으로 Numpy 패키지 설치없이 사용 가능

- 숫자 데이터를 좀 더 쉽고 편리하게 다룰 수 있음
- 숫자 데이터를 효과적으로 다룰 수 있기 때문에 데이터를 주로 다루는데 사용, 데이터 과학 및 데이터 분석에 많이 사용
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용

https://numpy.org/

### 넘파이 배열? ###

- 배열이란 순서가 있는 같은 종류의 데이터가 저장되는 자료형

### 리스트를 활용해도 되는데 넘파이를 왜 쓸까? ###
- 리스트도 좋은 자료형이지만 넘파이 배열이 구조적으로 속도가 빠르고 메모리를 적게 사용

<img src="http://jakevdp.github.io/images/array_vs_list.png" ></img>

>수 많은 숫자 데이터를 하나의 리스트 시퀸스로 다루게 되면 넘파이 베열에 비하여 상대적으로 속도가 느리고 메모리를 많이 차지하는 단점이 있음  
>넘파이 패키지 배열을 사용하면 리스트에 비해 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음  
>다만 넘파이 배열은 많은 데이터를 다룰 수 있다는 점에서 리스트와 비슷하면서 차이점  



<h3> 1. 모든 요소가 같은 자료형이어야 한다. </h3> 

<h3> 2. 요소의 개수 바꿀 수 있다. </h3>


- 넘파이 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠르며 벡터화 연산을 이용하여  
간단한 코드로 복잡한 연산을 수행 가능

<u> <h2> 넘파이 패키지 임포트하기 </h2> </u>

- np라는 이름으로 임포트하는 것이 관례
- 한번만 실행시키면 밑에 코드도 다 적용


```python
import numpy as np
```

- 넘파이 배열 객체인 ndarray는 N - dimensional Array의 약자 
- 1차원 배열, 2차원 배열 같은 다차원 배열 자료구조 지원

<u><h2> 1차원 배열 만들기 </h2></u>

- 넘파이의 array 메서드 인수로 시퀀스 자료형을 넣으면 ndarry 클래스 객체, 즉 넘파이 배열로 반환해줌 
- 시퀀스 자료형은 주로 튜플보단 리스트 많이 활용
- 만들어진 표현식을 보면 바깥쪽에 array()란 것이 붙을뿐 리스트와 동일한 구조처럼 보임


In [10]:
import numpy as np
ar = np.array([_ for _ in range(10)])
print(ar)

[0 1 2 3 4 5 6 7 8 9]


- 넘파이 배열 객체의 속성중 shape를 사용하면 넘파이 배열의 모양 확인 가능

In [12]:
ar.shape

(10,)

In [13]:
!conda list

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0    

In [19]:
# Numpy를 임포트
# jupyter lab에서 1회만 실행하면 그 아래 코드에선 다 사용 가능
import numpy as np

In [16]:
type(ar)

numpy.ndarray

> 리스트 자료형은 요소의 종류에 관계없이, 또 개수에 제한없이 삽입, 삭제, 수정 가능  
> 하지만 넘파이 배열 객체는 C언어의 배열처럼 메모리에서 연속적인 배치를 이루기 떄문에 모든 요소가 같은 자료형이어야 하고 개수가 명확해야함

In [17]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

# 넘파이의 자료형 #

In [21]:
ar2.dtype

dtype('float64')

In [22]:
ar.dtype

dtype('int32')

- 넘파이의 배열인 ndarray클래스는 요소가 모두 같은 자료형을 갖음
- 자료형을 명시적으로 작성하려면 키워드 인자로 dtype을 사용
- 반대로 dtype 키워드 인수가 없으면 해당 데이터 자료형을 동적 타이핑
- 만들어진 넘파이 배열의 자료형을 확인하려면 dtype 속성 활용

In [25]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8') #int8bytes --> 8*8bit
ar3

array([3, 6, 9], dtype=int64)

In [27]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [28]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자요형 중 제일 큰 값이 <U5이지만 <U8로 타입이 지정
ar5 = np.array(["가나다라마" for _ in range(5)], 'U5')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형

['가나다라마' '가나다라마' '가나다라마' '가나다라마' '가나다라마']
<U5


dtype접두사|설명|사용 예제|
|------|---|---|
|'?'|boolean|b(True, False)|
|'!'|int|i8(64비트)|
|'u'|unsigneo int|u8(64비트)|
|'f'|float| f8(64비트)|
|'c'|complex| c16(128비트)|
|'O'|Object| 0(객체에 대한 포인터)|
|'U'|Unicode string| U24(24 유니코드 글자)|

>첫번째 넘파이 배열에서 'f'를 활용하여 float로 dtype을 지정  
>dtype 속성을 활용해 타입을 확인하니 32비트의 float형으로 생성된 것을 확인가능  
>이 타입간 덧셈 연산의 결과는 숫자로 계산됨  
>바로 아래 넘파이 배열에서는 유니코들 문자열을 타입으로 지정해서 생성  
>1글자 이하의 글자들로 구성된 유니코드임을 추가적으로 설명  
>유니코드 간 덧셈은 concatenate의 결과를 보여줌  

In [47]:
x =  np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [49]:
x[0] + x[1]

3.0

In [50]:
x = np.array([1, 2, 3], dtype = "U")
x.dtype

dtype('<U1')

In [51]:
x[0] + x[1]

'12'

>넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan을 사용가능  
>다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf가 나옴  
>0을 0으로 나누려고 하면 np.nan이 나옴

In [33]:
np.array([0, 1, -1, 0]) / np .array([1, 0, 0, 0])

C:\Users\Playdata\AppData\Local\Temp\ipykernel_12476\3987597072.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np .array([1, 0, 0, 0])
C:\Users\Playdata\AppData\Local\Temp\ipykernel_12476\3987597072.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np .array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [34]:
np.log(0)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_12476\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [37]:
np.exp(-np.inf)

0.0

# [벡터화 연산] #

- 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원
- 리스트 내 모든 요소 데이터를 모두 2배 해야하는 경우 생각

In [43]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

- 넘파이 배열 객체의 벡터화 연산을 사용하면 다음돠 같이 for 반복문이 없이 간단하게 단 한번의 연산식으로 표현 가능
- 계산 속도도 리스트에 비해 빠름

In [52]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
2*x

array([2., 4., 6.], dtype=float32)

In [54]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [55]:
2 * a + b

array([12, 24, 36])

In [56]:
a == 2

array([False,  True, False])

In [57]:
b > 10

array([False,  True,  True])

In [60]:
(a == 2) & (b > 10) # $ 비트연산자

array([False,  True, False])

<u><h2> 2차원 배열 만들기 </h2></u>

> 2차원 배열은 수학에서 행렬이라고 함
>행렬에서는 가로줄을 행이라고 하고 세로줄을 열이라고 한다
>이와 비슷한 구조를 넘파이 배열은 통해 만들자

>다음과 같이 리스트를 중첩하여 리스트의 리스트를 이용해서 2차원 배열처럼 생성 가능
>안쪽 리스트의 길이는 행렬의 열의 수 즉 가로 크기가 되고, 바깥쪽 리스트의 길이는 행렬의 행의 수 즉 세로 크기가 됨

In [84]:
c = np.array([[0, 1, 2], [1, 2, 3]])
c

array([[0, 1, 2],
       [1, 2, 3]])

In [70]:
c.shape

(2, 3)

## 연습문제 ##

In [71]:
np.array([[10, 20, 30, 40], [50, 60, 70, 80]])


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<u><h2> 3차원 배열 만들기 </h2></u>

> ### 3차원 배열의 구조는 깊이 x 행 x 열 ###

In [75]:
# 2 x 3 x 4
d = np.array([[[1, 2, 3, 4],
              [5, 6, 7, 8,],
              [9, 10, 11, 12]],
             [[11, 12, 13, 14],
             [15, 16,17, 18],
             [19, 20, 21, 22]]])

In [76]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [78]:
#c = np.array([[0, 1, 2],[3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [80]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [89]:
다차원 배열일때

SyntaxError: invalid syntax (1010064183.py, line 1)

In [91]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [93]:
a [0, 0] # 첫 번째 행의 첫번째 열

0

In [94]:
a [0, 1] #첫 번째 헹의 두 번째 열

1

In [95]:
a [-1, -1] # 마지막 행의 마지막 열

5

# 배열의 슬라이싱 #

- 다차원 배열의 복수 개를 접근하려면 슬라이싱과 comma(,) 함께 사용

In [103]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [105]:
a[0, :] # 첫번쨰 행 전체

array([0, 1, 2, 3])

In [106]:
a[:, 1] #두번째 열 전체

array([1, 5])

In [107]:
a[1, 1:] # 두번쨰 행 두번째 열부터 끝까지

array([5, 6, 7])

In [108]:
np.array([_ for _ in range(8)]).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [110]:
m = np.array([_ for _ in range(15)]).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

-----------------------

## 연습문제 ##

In [117]:
m[1, 2]

7

In [118]:
m[2, 4]

14

In [125]:
m[1, 1:3]

array([6, 7])

In [131]:
m[1:3, 2]

array([ 7, 12])

In [132]:
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

-----------------------

### 배열 생성 ### 

>Numpty는 몇가지 단순한 배열을 성성하는 메소드가 있음

- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace
- zeros

In [136]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [137]:
b = np.zeros((5,2), dtype='i')
b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [138]:
c = np.zeros(5, dtype ="U4")
c

array(['', '', '', '', ''], dtype='<U4')

In [139]:
c[0] = "abc"
c[1] = "abcd"
c[2] = "ABCDE"
c

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [151]:
d = np.ones((2, 3, 4), dtype ="i8")
d        #(깊이, 행 ,열)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [152]:
e = np.ones_like (d, dtype = "e")
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

In [146]:
f = np.empty((4, 3))
f

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

## arange 명령 ##

In [148]:
np. arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
np.arange(3, 21, 2) # 시작, 끝(포함 x), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [154]:
np.linspace(0, 100, 20) #갯수에 맞춰 간격을 동일하게 잘라줌

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [155]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [156]:
ex2 = np.logspace(0, 100, 5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

## 전치 연산
--> 행과 열을 바꾼다.

In [159]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형 ##

- 1차원 배열을 다차원으로 만들땐 reshape 사용

In [170]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [165]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [168]:
a = np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [169]:
b = a.reshape(3, 4)   #shape을 맞춰서 만들어줘야한다
b                     #맞지않으면 오류가 뜬다

ValueError: cannot reshape array of size 13 into shape (3,4)

- 다차원 배열은 1차원으로 만들땐 flatten 혹은 ravel 메서드 사용

In [172]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [173]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 차원만 1차원 증가시키기


In [177]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [183]:
x[ :, np.newaxis ]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결 ###

> 두 개 이상의 배열을 연결하여 더 큰 배열을 만들 때

- hstack
- vstack
- dstack
- stack
- r__
- c__
- tile

### 1. hstack : 옆으로 붙여 나가는 방식, 행의 갯수는 일치해야 함 ###

In [201]:
import numpy as np

a1 = np.ones((2, 3))
print(a1)

a2 = np.ones((2, 2))
print(a2)

hs = np.hstack([a1, a2])
print(hs)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 2. vstack : 밑으로 붙여 나가는 방식, 열의 갯수는 일치해야 함 ###

In [202]:
b1 = np.ones((2, 3))
print(b1)

b2 = np.ones((3, 3))
print(b2)

vs = np.vstack([b1, b2])
print(vs)


[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3. dstack : 제 3의 축방향으로 배열 결합 , depth ###

In [208]:
c1 = np.zeros((3, 4))
print(c1)

c2 = np.ones((3, 4))
print(c2)

# 2개의 3x4 배열이 1개의 3x4x2로 생성

ds = np.dstack([c1, c2])
print(ds)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]]


### 4. stack : 사용자가 지정한 방향을 배열을 연결 ###

In [204]:
# axis 인수를 사용하여 연결후의 회전 방향을 결정

s1 = np.stack([c1, c2])
print(s1)

s2 = np.stack([c1, c2], axis=1)
print(s2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [1. 1. 1. 1.]]]


### 5.인덱서 r_ : () 대신 [] 사용, 특수매서드 ###

In [205]:
ruh = np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]
print(ruh)

[1 2 3 4 5 6]


### 6. c_ : 배열의 차원을 증가 시킨후 연결 ###

In [206]:
cuh = np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]
print(cuh)

[[1 4]
 [2 5]
 [3 6]]


### 7. tile : 동일한 배열을 반복해서 연결 ###

In [211]:
ti = np.array([[1, 2, 3], [4, 5, 6]])
print(np.tile(ti, 5))
print(np.tile(ti, (3, 2)))

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]]


[출처]  [파이썬 데이터분석] 배열 연결|작성자 EASYCODING


In [234]:
import numpy
a1 = np.zeros((3, 3))
a2 = np.ones((3, 2))
a3 = np.hstack([a1, a2])
a4 = np.arange(10, 160, 10)
a5 = a4.reshape(3, 5)
a6 = np.vstack([a3, a5])
print(np.tile(a6, (2, 1)))

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]
